name: practice
on: push
job:
  practice-job:
  name: test_one
  runs-on: ubuntu-latest
  steps:
    uses: actions/checkout@v2
    uses: actions/setup-python@v3
    python -m pip install --upgrade pip
    pip3 install -r requirement.txt
    python3 server.py > log.txt 2>&1 &
